services:
  ros-foxy-turtlebot3:
    image: ros_foxy_turtlebot3
    privileged: true
    build: 
      context: .
      dockerfile: ./Dockerfile
      network: host  # <-- Añade esta línea
    container_name: cont_ros_foxy_turtlebot3
    environment:
      - QT_X11_NO_MITSHM=1
    volumes:
      # PERMISSIONS
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      # WORKSPACE (solo lectura)
      - ./notebook:/ros2_ws/notebook:ro
      # WORKSPACE
      - ./.devcontainer/.vscode:/ros2_ws/.vscode:rw
      - ./proyecto_ros:/ros2_ws/src
    network_mode: "host"

